# -*- mode: ruby -*-
# vi: set ft=ruby :
##
# @file This file is part of EDGE.
#
# @author Alexander Breuer (anbreuer AT ucsd.edu)
#
# @section LICENSE
# Copyright (c) 2018, Regents of the University of California
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# @section DESCRIPTION
# Vagrant configuration, which allows to run Singularity in user space through a virtual machine.
#   1) Fire up the machine by running `vagrant up`.
#   2) Run the bootstrap (time consuming) `vagrant ssh -c "sudo singularity build edge.simg /vagrant/debian.def"`.
#   3) Copy the container to the host: `vagrant ssh -c "cat /home/vagrant/edge.simg" > ./edge.simg` 
##

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  config.vm.provider "virtualbox" do |vb|
    # 2GB of memory required for compilation
    vb.memory = "2048"

    # limit to single VPU
    vb.cpus = 1
  end

  # bootstrap, which installs Singularity.
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -qq -o=Dpkg::Use-Pty=0 python
    sudo apt-get install -qq -o=Dpkg::Use-Pty=0 dh-autoreconf
    sudo apt-get install -qq -o=Dpkg::Use-Pty=0 build-essential
    sudo apt-get install -qq -o=Dpkg::Use-Pty=0 libarchive-dev
    sudo apt-get install -qq -o=Dpkg::Use-Pty=0 git
    sudo apt-get install -qq -o=Dpkg::Use-Pty=0 squashfs-tools
    sudo apt-get install -qq -o=Dpkg::Use-Pty=0 debootstrap
    git clone https://github.com/singularityware/singularity.git
    cd singularity
    ./autogen.sh
    ./configure --prefix=/usr/local --sysconfdir=/etc
    make
    sudo make install
    cd ..
    rm -rf singularity
  SHELL
end