# path for UCVMC lib
UCVMDIR ?= $(HOME)/workspace/edge/velocity_model/UCVMC/ucvm-17.1.0

# path for Proj.4 lib
PROJ4DIR ?= $(UCVMDIR)/lib/proj-4

# path for MOAB lib
MOABDIR ?= $(HOME)/workspace/edge/submodules/libs/
#MOABDIR ?= $(HOME)/moab/build
